# Generated by Django 4.1.3 on 2022-11-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sobrante', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('hora', models.TimeField()),
                ('ingreso', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='nomina_app.tecnico')),
                ('tipoTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='nomina_app.tipotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('comentarios', models.CharField(max_length=255)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezasAPagar', to='nomina_app.dia')),
            ],
        ),
        migrations.CreateModel(
            name='OtroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('comentarios', models.CharField(max_length=255)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrosGastos', to='nomina_app.dia')),
            ],
        ),
        migrations.AddField(
            model_name='dia',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='nomina_app.semana'),
        ),
    ]
