# Generated by Django 4.1.3 on 2022-11-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='dia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='nomina_app.dia'),
            preserve_default=False,
        ),
    ]
