# Generated by Django 4.1.3 on 2022-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_app', '0002_venta_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semana',
            name='abierta',
            field=models.BooleanField(default=False),
        ),
    ]
