# Generated by Django 4.1.3 on 2022-11-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_app', '0003_dia_abierto_semana_abierta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='sobrante',
            field=models.IntegerField(null=True),
        ),
    ]
