# Generated by Django 4.1.3 on 2022-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_app', '0004_alter_dia_sobrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrogasto',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piezaapagar',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ingreso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
